name = "planner-cloudflare-api"
main = "services/index.js"
compatibility_date = "2026-01-27"
compatibility_flags = ["nodejs_compat"]
minify = true
workers_dev = true
preview_urls = true
routes = ["planner-cloudflare.pages.dev/api/*"]

# Configure routes in Cloudflare to point /api/* to this worker.
